services:
  postgres:
    image: postgres:18-alpine
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_APP_USER: ${DB_APP_USERNAME}
      POSTGRES_APP_PASSWORD: ${DB_APP_PASSWORD}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_TEST_DB: ${DB_TEST_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      # Updated for Postgres 18: mounted to the base directory
      - postgres_data:/var/lib/postgresql
      - ./docker-init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: local_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    container_name: local_mailpit
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_MAX_MESSAGES: 500
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "1025" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  redis_data:
