#!/bin/bash
set -e

# Perform all actions as the default postgres user
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE "$POSTGRES_APP_USER" LOGIN PASSWORD '$POSTGRES_APP_PASSWORD'
    NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
    CREATE DATABASE "$POSTGRES_TEST_DB" OWNER "$POSTGRES_APP_USER";
EOSQL
